### PR TITLE
Feature/rs compatiblility

### PR DESCRIPTION
**Pull request by toelo3**
Convert JKS files to PEM to make it compatible with Rust SDK

Add tenant-vpn-dsh-linux-2.5.8-4-rs-k8s.tar.gz
- Adds a script to convert JKS files to PEM files to make it compatible with Rust SDK
  - triggers directly from getjks.sh
- Add to $PKI_CONFIG_DIR to initconfig.sh
-  Fixed bug that it picks up ca.crt instead of keystore.jks in the getjks.sh

### CODE REVIEW

**Comment by rafhuys-klarrio** [comment]
@toelo3 

I would remove the reference to the HOME dir

```
sudo "${HOME}"/.vpn/convertjkstocerts.sh ...
```

to something like

```
SCRIPT_DIR=$(dirname "${BASH_SOURCE[0]}")
source "${SCRIPT_DIR}/convertjkstocerts.sh"
```

**Comment by toelo3** [comment]
@rafhuys-klarrio  thanks, i have changed it your suggestion and tested it

**Comment by rafhuys-klarrio** [comment]
okido! This repo only contains the artifacts of the upstream private repo, so I can't just merge your PR here. We'll do that and release the update here soon. 

Thanks for your contribution!!

**Comment by toelo3** [comment]
Great! Thanks for looking into :) i'll close this PR for now

**Pull request closed without merging**
